### ISSUE TITLE
TrimFiles task throws exceptions

### ISSUE THREAD

**Issue by wjk** [ericstj/Microsoft.Packaging.Tools.Trimming#3]
The `TrimFiles` task throws two exceptions when I try to use it. Zipped binlog is attached.

1. Root package Microsoft.Packaging.Tools.Trimming was specified but was not found in PackageDependencies
2. An item with the same key has already been added. Key: Microsoft.Win32.Registry.dll

[msbuild.binlog.zip](https://github.com/ericstj/Microsoft.Packaging.Tools.Trimming/files/2810553/msbuild.binlog.zip)

**Comment by ericstj** [comment]
Thanks, I'll take a look.

**Comment by wjk** [comment]
This no longer occurs.
